App\Entity\Location:
    properties:
        latitude:
            - NotBlank: ~
            - Range:
                min: -90
                max: 90
                groups: [new, edit]
            - Type: decimal
        longitute:
            -   NotBlank: ~
            -   Range:
                    min: -180
                    max: 180
                    groups: [new, edit]
            - Type: decimal

App\Entity\Forecast:
    properties:
        tempaeratureCelsius:
            -   NotBlank: ~
            -   Range:
                    min: -200
                    max: 200
                    groups: [ new, edit ]
            -   Type: integer
        humidity:
            -   NotBlank: ~
            -   Range:
                    min: 0
                    max: 100
                    groups: [ new, edit ]
            -   Type: integer
        windSpeed:
            -   NotBlank: ~
            -   Type: integer
            -   PositiveOrZero:
                    groups: [ new, edit ]
        pressure:
            -   NotBlank: ~
            -   Type: integer
            -   PositiveOrZero:
                    groups: [ new, edit ]
