controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

#custom route
#weather_highlander:
#    path: /weather/highlander
#    controller: App\Controller\WeatherController::index
